apiVersion: v1
kind: Service
metadata: 
  name: train-schedule service
spec:
  selector: 
    app: train-schedule
  ports:
      type: NodePort
    - protocol: TCP
      NodePort: 8080
      targetPort: 8080
      
---

apiVersion: v1
kind: Deployment
metadata:
  name: train-schedule
  app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec: 
  containers:
   - name: train-shedule
     image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
     ports: 
     - containerPort: 8080
