apiVersion: v1
kind: Service
metadata: 
  name: train-schedule service
spec:
  selector: 
    app: train-schedule
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      
---

apiVersion: v1
kind: Pod
metadata:
  name: train-schedule
  app: train-schedule
spec:
  containers:
   - name: train-shedule
     image: ilyalirtsman/train-schedule:latest
     ports: 
     - containerPort: 80
